Document: syutil
Title: Debian syutil Manual
Author: <insert document author here>
Abstract: This manual describes what syutil is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/syutil/syutil.sgml.gz

Format: postscript
Files: /usr/share/doc/syutil/syutil.ps.gz

Format: text
Files: /usr/share/doc/syutil/syutil.text.gz

Format: HTML
Index: /usr/share/doc/syutil/html/index.html
Files: /usr/share/doc/syutil/html/*.html
